import { Inventory } from "@types";

export const inventory: Inventory[] = [
  {
    id: 0, 
    hash: "Hot Head #000",
    pfp: ["BTU8LK0V_4sVr8yh40LRPAGS_NVBADF9aDPbcq-lQMw.png", "Hot_Head_Devil_by_Mellow.png", "Hot_Heads_comms.png", "Hot_Heads_Devil.png", "hothead_character_000.png"],
    banners:["Angel_vs_Devil.png"],
    wallpapers: ["FnRCaosX0BYT5gE.jpg", "Underworld.png"],
    memes:[],
  },
  {
    id: 1, 
    hash: "Hot Head #001",
    pfp: ["image.png"],
    banners:["001.jpg"],
    wallpapers: [],
    memes:[],
  },
  {
    id: 2, 
    hash: "Hot Head #002",
    pfp: ["Hot_Head_002_by_Ivory_Magic.png","image.png"],
    banners:["002.jpg"],
    wallpapers: [],
    memes:[],
  },
  {
    id: 3, 
    hash: "Hot Head #003",
    banners:["003.jpg","IMG_1572.png"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 4, 
    hash: "Hot Head #004",
    banners:["004.jpg"],
    memes:["4.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 5, 
    hash: "Hot Head #005",
    banners:["005.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: ["image0.jpg"],
  },
  {
    id: 6, 
    hash: "Hot Head #006",
    banners:["006.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 7, 
    hash: "Hot Head #007",
    banners:["007.jpg"],
    memes:[],
    pfp: ["Hot_Head_007.png","image.png"],
    wallpapers: [],
  },
  {
    id: 8, 
    hash: "Hot Head #008",
    banners:["008.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 9, 
    hash: "Hot Head #009",
    banners:["009.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 10, 
    hash: "Hot Head #010",
    banners:["010.jpg"],
    memes:[],
    pfp: ["Fks5j0paEAA1ynx.jpg","Fo5LP9QaYAAF-AP.png","FoPWoPzXkAA7w4V.jpg","image.png","lUEmWUROC2TqKlcLG3-WYRq3av9r0RwD_OjDlRQeG6s.png"],
    wallpapers: [],
  },
  {
    id: 11, 
    hash: "Hot Head #011",
    banners:["011.jpg"],
    memes:["11.png"],
    pfp: ["Hot_Heads_Bomber.png","image.png"],
    wallpapers: [],
  },
  {
    id: 12, 
    hash: "Hot Head #012",
    banners:["012.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 13, 
    hash: "Hot Head #013",
    banners:["013.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 14, 
    hash: "Hot Head #014",
    banners:["014.jpg"],
    memes:["14.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 15, 
    hash: "Hot Head #015",
    banners:["131506F8-A764-4BE6-BE92-46AB01726263.jpg"],
    memes:["01EBB8B6-B2B5-45BD-A987-D7EC8590FD37.jpg","15.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 16, 
    hash: "Hot Head #016",
    banners:["016.jpg"],
    memes:[],
    pfp: ["HH_Animated_GIF.gif", "image.png"],
    wallpapers: [],
  },
  {
    id:17, 
    hash: "Hot Head #017",
    banners:["017.jpg"],
    memes:[],
    pfp: ["bafkreidbt3aafw6hpufpsr5i7wnop3sy3xbeiedirimmle7afrgm4e2uiu.png", "Hot_Head_3D_by_Gang_Leader.mp4"],
    wallpapers: [],
  },
  {
    id: 18, 
    hash: "Hot Head #018",
    banners:["018.jpg"],
    memes:["18.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 19, 
    hash: "Hot Head #019",
    banners:["019.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  // 20's 
  {
    id: 20, 
    hash: "Hot Head #020",
    banners:["020.jpg"],
    memes:["20.png", "Khong_Co_Tieu_e565_20230316111427.png"],
    pfp: ["0F1EE31D-FF14-45DE-A99A-F469FD04DEE8.jpg","image.png"],
    wallpapers: [],
  },
  {
    id: 21, 
    hash: "Hot Head #021",
    banners:["021.jpg"],
    memes:[],
    pfp: ["cobb.gif","image.png", "DEFA4C3C-7A9D-43F4-A20C-4F1E3F1B72B6.jpg","Hot_Head_SOL_3D_Head.mov"],
    wallpapers: [],
  },
  {
    id: 22, 
    hash: "Hot Head #022",
    banners:["022.jpg"],
    memes:["22.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 23, 
    hash: "Hot Head #023",
    banners:["023.jpg"],
    memes:["23.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 24, 
    hash: "Hot Head #024",
    banners:["024.jpg"],
    memes:["24.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 25, 
    hash: "Hot Head #025",
    banners:["025.jpg"],
    memes:["25.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 26, 
    hash: "Hot Head #026",
    banners:["026.jpg"],
    memes:["26.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:27, 
    hash: "Hot Head #027",
    banners:["027.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 28, 
    hash: "Hot Head #028",
    banners:["028.jpg"],
    memes:["28.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 29, 
    hash: "Hot Head #029",
    banners:["029.jpg"],
    memes:["29.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  // 30's 
  {
    id: 30, 
    hash: "Hot Head #030",
    banners:["030.png"],
    memes:["30.png"],
    pfp: ["pSKBafhmlmuCipSt5HQM9n-WyFeYTg7TCzQWzY5yPdA.png","image.png"],
    wallpapers: ["image0.jpg"],
  },
  {
    id: 31, 
    hash: "Hot Head #031",
    banners:["031.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 32, 
    hash: "Hot Head #032",
    banners:["032.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 33, 
    hash: "Hot Head #033",
    banners:["033.jpg","IMG_0100.jpg"],
    memes:[],
    pfp: ["image.png","IMG_2683.jpg"],
    wallpapers: [],
  },
  {
    id:34, 
    hash: "Hot Head #34",
    banners:["034.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 35, 
    hash: "Hot Head #035",
    banners:["035.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 36, 
    hash: "Hot Head #036",
    banners:["036.jpg"],
    memes:["36.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:37, 
    hash: "Hot Head #037",
    banners:["037.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 38, 
    hash: "Hot Head #038",
    banners:["038.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 39, 
    hash: "Hot Head #039",
    banners:["039.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  // 40's 
  {
    id: 40, 
    hash: "Hot Head #040",
    banners:["040.jpg"],
    memes:["40.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 41, 
    hash: "Hot Head #041",
    banners:["041.jpg"],
    memes:["41.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 42, 
    hash: "Hot Head #042",
    banners:["042.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 43, 
    hash: "Hot Head #043",
    banners:["043.jpg"],
    memes:["43.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:44, 
    hash: "Hot Head #44",
    banners:["044.jpg"],
    memes:["44.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 45, 
    hash: "Hot Head #045",
    banners:["045.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 46, 
    hash: "Hot Head #046",
    banners:["046.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:47, 
    hash: "Hot Head #047",
    banners:["047.jpg"],
    memes:["47.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 48, 
    hash: "Hot Head #048",
    banners:["048.jpg"],
    memes:["48.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 49, 
    hash: "Hot Head #049",
    banners:["49.jpg"],
    memes:["49.png"],
    pfp: ["image.png","FireScarf-0001.gif"],
    wallpapers: [],
  },
  // 50's 
  {
    id: 50, 
    hash: "Hot Head #050",
    banners:["50.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 51, 
    hash: "Hot Head #051",
    banners:["51.jpg","VoH55D0k.png"],
    memes:[],
    pfp: ["image.png","FlyCodeine.gif"],
    wallpapers: [],
  },
  {
    id: 52, 
    hash: "Hot Head #052",
    banners:["52.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 53, 
    hash: "Hot Head #053",
    banners:["53.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:54, 
    hash: "Hot Head #54",
    banners:["54.jpg"],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 55, 
    hash: "Hot Head #055",
    banners:[],
    memes:["55.png","FqVWa9FaYAAjxoY.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 56, 
    hash: "Hot Head #056",
    banners:[],
    memes:["56.png"],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:57, 
    hash: "Hot Head #057",
    banners:["57.jpg"],
    memes:[],
    pfp: ["image.png","IMG_0812.gif"],
    wallpapers: [],
  },
  {
    id: 58, 
    hash: "Hot Head #058",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 59, 
    hash: "Hot Head #059",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  // 60's 
  {
    id: 60, 
    hash: "Hot Head #060",
    banners:[],
    memes:[],
    pfp: ["Hot_Head_060-animate.gif","image.png"],
    wallpapers: [],
  },
  {
    id: 61, 
    hash: "Hot Head #061",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 62, 
    hash: "Hot Head #062",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 63, 
    hash: "Hot Head #063",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id:64, 
    hash: "Hot Head #64",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 65, 
    hash: "Hot Head #065",
    banners:[],
    memes:[],
    pfp: ["image.jpg"],
    wallpapers: [],
  },
  {
    id: 66, 
    hash: "Hot Head #066",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },
  {
    id:67, 
    hash: "Hot Head #067",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },
  {
    id: 68, 
    hash: "Hot Head #068",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },
  {
    id: 69, 
    hash: "Hot Head #069",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 70, 
    hash: "Hot Head #070",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 71, 
    hash: "Hot Head #071",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 72, 
    hash: "Hot Head #072",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 73, 
    hash: "Hot Head #073",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 74, 
    hash: "Hot Head #074",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 75, 
    hash: "Hot Head #075",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 76, 
    hash: "Hot Head #076",
    banners:[],
    memes:[],
    pfp: ["image.webp"],
    wallpapers: [],
  },{
    id: 77, 
    hash: "Hot Head #077",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },{
    id: 78, 
    hash: "Hot Head #078",
    banners:[],
    memes:[],
    pfp: ["image.png"],
    wallpapers: [],
  },{
    id: 79,
    hash: "Hot Head #079",
    banners:[],
    memes:[],
    pfp: ["/images/hotheads/hh_79/PFP/image.jpg"],
    wallpapers: [],
  },{
    id: 80,
    hash: "Hot Head #080",
    banners:[],
    memes:[],
    pfp: ["/images/hotheads/hh_80/PFP/image.png"],
    wallpapers: [],
  },{
    id: 81,
    hash: "Hot Head #081",
    banners:[],
    memes:[],
    pfp: ["/images/hotheads/hh_81/PFP/image.png"],
    wallpapers: [],
  }
];
